image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000-8999
    onOpen: notify
tasks:
  - name: GanacheCLI
    init:  >
      npm install -g ganache-cli &&
      gp sync-done stepone
  - init: npm install web3
